from pyspark.sql import DataFrame, SparkSession
from pyspark.sql.functions import col, when

def integrate_data(df: DataFrame, spark: SparkSession) -> DataFrame:
    """
    Menggabungkan dataset transaksi dengan sumber data eksternal (mapping benua/Region)
    menggunakan native Spark SQL functions untuk menghindari overhead Python Worker di Windows.
    """
    df_integrated = df.withColumn(
        "Region",
        when(col("Country") == "UNITED KINGDOM", "Europe")
        .when(col("Country") == "GERMANY", "Europe")
        .when(col("Country") == "FRANCE", "Europe")
        .when(col("Country") == "AUSTRALIA", "Oceania")
        .when(col("Country") == "JAPAN", "Asia")
        .when(col("Country") == "SAUDI ARABIA", "Asia") 
        .when(col("Country") == "SPAIN", "Europe")
        .when(col("Country") == "PORTUGAL", "Europe")
        .when(col("Country") == "ITALY", "Europe") 
        .when(col("Country") == "SWITZERLAND", "Europe")
        .when(col("Country") == "BELGIUM", "Europe")
        .when(col("Country") == "NETHERLANDS", "Europe")
        .when(col("Country") == "EIRE", "Europe")
        .when(col("Country") == "USA", "North America")
        .when(col("Country") == "LEBANON", "Asia")
        .when(col("Country") == "BRAZIL", "South America")
        .when(col("Country") == "ICELAND", "Europe")
        .when(col("Country") == "JAPAN", "Asia")
        .when(col("Country") == "HONG KONG", "Asia")
        .when(col("Country") == "SINGAPORE", "Asia")
        .when(col("Country") == "CHANNEL ISLANDS", "Europe")
        .when(col("Country") == "CYPRUS", "Europe")
        .when(col("Country") == "NORWAY", "Europe")
        .when(col("Country") == "POLAND", "Europe")
        .when(col("Country") == "SWEDEN", "Europe")
        .when(col("Country") == "DENMARK", "Europe")
        .when(col("Country") == "AUSTRIA", "Europe")
        .when(col("Country") == "IRELAND", "Europe")
        .when(col("Country") == "BAHRAIN", "Asia")
        .when(col("Country") == "RSA", "Africa")
        .when(col("Country") == "MALAYSIA", "Asia")
        .when(col("Country") == "ARGENTINA", "South America")
        .when(col("Country") == "UNITED ARAB EMIRATES", "Asia")
        .when(col("Country") == "ALBANIA", "Europe")
        .when(col("Country") == "FINLAND", "Europe")
        .when(col("Country") == "ISRAEL", "Asia")
        .when(col("Country") == "GREECE", "Europe")
        .when(col("Country") == "CZECH REPUBLIC", "Europe")
        .when(col("Country") == "CANADA", "North America")
        .when(col("Country") == "MALTA", "Europe")
        .when(col("Country") == "LUXEMBOURG", "Europe")
        .when(col("Country") == "KENYA", "Africa")
        .when(col("Country") == "EGYPT", "Africa")
        .when(col("Country") == "KOREA, REPUBLIC OF", "Asia")
        .when(col("Country") == "PORTUGAL", "Europe")
        .when(col("Country") == "COSTA RICA", "North America")
        .when(col("Country") == "PORTUGAL", "Europe")
        .when(col("Country") == "HUNGARY", "Europe")
        .otherwise("Other")
    )
    
    return df_integrated
